version: '3.4'

networks:
  demoauditapp:

services:
  demoappdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Qwerty123#
    networks:
      - demoauditapp
  audit:
    container_name: audit
    image: ${DOCKER_REGISTRY-}audit
    build:
      context: .
      dockerfile: Audit/Dockerfile
    ports:
      - 8001:8080
    depends_on:
      - demoappdb
    # environment:
    #  - DB_HOST = demoappdb
    #  - DB_NAME = audit
    #  - DB_SA_PASSWORD = Qwerty123#
    networks:
    - demoauditapp